# Generated by Django 3.2.3 on 2021-05-29 05:00

import api.models.item_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210529_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo_url', models.ImageField(blank=True, help_text='Image of item', null=True, upload_to=api.models.item_model.item_photo_upload_handler)),
                ('is_available', models.BooleanField(default=False)),
                ('additional_detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Size', max_length=255)),
                ('mrp', models.PositiveIntegerField(default=1, help_text='MRP (price)')),
                ('additional_detail', models.CharField(help_text='Any description of size (max 50 letter)', max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of tag Like VEG, NON-VEG, LOW-FAT, CARBS ', max_length=100)),
                ('description', models.CharField(blank=True, help_text='for eg. Veg item/ Non veg item/ Low fat food etc', max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='merchandise',
        ),
        migrations.AddField(
            model_name='category',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.category'),
        ),
    ]
