# Generated by Django 3.2.3 on 2021-05-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_merchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], default='UNPAID', max_length=100)),
                ('payment_link', models.CharField(default='', max_length=256)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.merchandise')),
            ],
        ),
    ]
